name: Update version
description: Update version

inputs:
  version:
    description: Release version
  file:
    description: File to update
    default: ./cli/Cargo.toml

runs:
  using: composite
  steps:
    - name: Update version
      env:
        VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        sed -i.bak "s/0.0.0/$VERSION/g" ${{ inputs.file }}
