[package]
name = "context_ruby"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.93"
context = { path = "../../../context", features = ["git-access", "ruby"] }
test_report = { path = "../../../test_report", features = ["ruby"] }
magnus = { version = "0.7" }
