name: Optimize CLI Binary
description: Compress CLI binary using UPX

inputs:
  target:
    description: Rust target triple, e.g. x86_64-apple-darwin
  profile:
    description: Rust profile to build, e.g. release-with-debug

runs:
  using: composite
  steps:
    - name: Compress binary
      shell: bash
      run: |
        if [[ "${{ inputs.target }}" == *"windows-gnu"* ]]; then
          # Windows binaries use .exe extension
          upx --best --lzma target/${{ inputs.target }}/${{ inputs.profile }}/trunk-analytics-cli.exe
        else
          upx --best --lzma target/${{ inputs.target }}/${{ inputs.profile }}/trunk-analytics-cli
        fi

    - name: Report binary size
      shell: bash
      run: |
        if [[ "${{ inputs.target }}" == *"windows-gnu"* ]]; then
          ls -lh target/${{ inputs.target }}/${{ inputs.profile }}/trunk-analytics-cli.exe
        else
          ls -lh target/${{ inputs.target }}/${{ inputs.profile }}/trunk-analytics-cli
        fi
