name: Upload artifact to S3
description: Upload artifact to S3
inputs:
  name:
    description: Name of the artifact to upload
    required: true
  path:
    description: Path to the artifact to upload
    required: true
  bucket:
    description: S3 bucket to upload the artifact to
    required: true
  role-to-assume:
    description: ARN of the role to assume
    required: false
  s3-flags:
    description: Additional flags to pass to the `aws s3 cp` command
    required: false

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        aws-region: us-west-2

    - name: Upload artifact to S3
      shell: bash
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        DATE=$(date "+%Y-%m-%d")
        LOCAL_FILE=${{ inputs.path }}
        TARGET_PATH="${{ inputs.bucket }}/${DATE}/${GIT_SHA}/${{ inputs.name }}"

        aws s3 cp ${{ inputs.s3-flags }} ${LOCAL_FILE} s3://${TARGET_PATH}
