name: Upload artifact to S3
description: Upload artifact to S3
inputs:
  name:
    description: Name of the artifact to upload
    required: true
  path:
    description: Path to the artifact to upload
    required: true
  bucket:
    description: S3 bucket to upload the artifact to
    required: true
  role-to-assume:
    description: ARN of the role to assume
    required: false
  compress:
    description: Whether to compress the artifact before uploading
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        aws-region: us-west-2

    - name: Compress input
      shell: bash
      if: ${{ inputs.compress == 'true' }}
      run: |
        TAR_FILE="${{ inputs.name }}"
        tar -czvf "${TAR_FILE}" -C ${{ inputs.path }} .
        echo "Compressed folder ${{ inputs.path }} to ${TAR_FILE}"
        echo TAR_FILE=${TAR_FILE}>> $GITHUB_ENV

    - name: Upload artifact to S3
      shell: bash
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        DATE=$(date "+%Y-%m-%d")
        LOCAL_FILE=${TAR_FILE:-${{ inputs.path }}}

        aws s3 cp ${LOCAL_FILE} s3://${{ inputs.bucket }}/${DATE}/${GIT_SHA}/${{ inputs.name }}
