name: Upload test results
description: Upload test results

inputs:
  target:
    description: Rust target triple, e.g. x86_64-apple-darwin
  sentry-org:
    description: Sentry organization
  sentry-project:
    description: Sentry project
  sentry-auth-token:
    description: Sentry auth token

runs:
  using: composite
  steps:
    - name: Cache sentry-cli
      uses: actions/cache@v4
      id: cache-sentry-cli
      with:
        path: ~/.local/bin/sentry-cli
        key: sentry-cli-latest

    - name: Install sentry-cli
      if: steps.cache-sentry-cli.outputs.cache-hit != 'true'
      shell: bash
      run: curl -sL --retry 5 --retry-all-errors --retry-delay 2 https://sentry.io/get-cli/ | sh

    - name: Upload debug info to Sentry
      shell: bash
      run: sentry-cli debug-files upload --include-sources target/${{ inputs.target }}/release-with-debug/trunk-analytics-cli.debug --org=${{ inputs.sentry-org }} --project=${{ inputs.sentry-project }} --auth-token=${{ inputs.sentry-auth-token }}
