name: Run tests
description: Run tests

inputs:
  target:
    description: Rust target triple, e.g. x86_64-apple-darwin
  codecov-token:
    description: Codecov secret, used for uploads

runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@cargo-llvm-cov

    - name: Install nextest (darwin)
      if: contains(inputs.target, 'darwin')
      uses: taiki-e/install-action@nextest

    - name: Cache nextest binary
      uses: actions/cache@v4
      id: cache-nextest
      with:
        path: ~/.cargo/bin/cargo-nextest
        key: nextest-${{ inputs.target }}-latest

    - name: Install nextest (linux x86)
      if: (inputs.target == 'x86_64-unknown-linux-musl' || inputs.target == 'x86_64-unknown-illumos' || inputs.target == 'x86_64-pc-windows-gnu') && steps.cache-nextest.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${CARGO_HOME:-~/.cargo}/bin
        curl -LsSf --retry 5 --retry-all-errors --retry-delay 2 https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Install nextest (linux arm64)
      if: inputs.target == 'aarch64-unknown-linux-musl' && steps.cache-nextest.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${CARGO_HOME:-~/.cargo}/bin
        curl -LsSf --retry 5 --retry-all-errors --retry-delay 2 https://get.nexte.st/latest/linux-arm | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Collect coverage data (including doctests)
      shell: bash
      run: |
        set +e
        cargo llvm-cov --no-report nextest --features=bindings --workspace ${{ contains(inputs.target, 'musl') && '--exclude context-js --exclude context-py' || '' }} --profile=ci
        exitcode="$?"
        cargo llvm-cov --no-report --doc
        cargo llvm-cov report --doctests --lcov --output-path lcov.info
        exit "$exitcode"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: always()
      with:
        token: ${{ inputs.codecov-token }}
        slug: trunk-io/analytics-cli
        files: lcov.info
