name: Run tests
description: Run tests

inputs:
  target:
    description: Rust target triple, e.g. x86_64-apple-darwin

runs:
  using: composite
  steps:
    - name: Install nextest (darwin)
      if: contains(inputs.target, 'darwin')
      uses: taiki-e/install-action@nextest

    - name: Install nextest (linux x86)
      if: inputs.target == 'x86_64-unknown-linux-musl'
      shell: bash
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Install nextest (linux arm64)
      if: inputs.target == 'aarch64-unknown-linux-musl'
      shell: bash
      run: curl -LsSf https://get.nexte.st/latest/linux-arm | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Run tests
      shell: bash
      run: cargo nextest run --workspace ${{ contains(inputs.target, 'musl') && '--exclude context-js --exclude context-py --exclude context_ruby' || '' }} --profile=ci
