name: Build CLI Tools
description: Build bundle, xcresult, and codeowners CLI tools for the specified target.

inputs:
  target:
    description: Rust target triple, e.g. x86_64-apple-darwin
    required: true
  os-name:
    description: Operating system name for conditional building
    required: true
  release_tag:
    description: Release tag for version updates
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Add target for CLI tools
      shell: bash
      run: rustup target add ${{ inputs.target }}

    - name: Install MinGW for Windows cross-compilation
      shell: bash
      if: ${{ contains(inputs.target, 'windows-gnu') }}
      run: |
        sudo apt-get update
        # Install build-essential for host build scripts (cc/gcc)
        # Install gcc-mingw-w64-x86-64 for Windows target cross-compilation
        sudo apt-get install -y build-essential gcc-mingw-w64-x86-64

    - name: Install musl development tools
      shell: bash
      run: |
        if [[ "${{ inputs.target }}" == *"musl"* ]]; then
          sudo apt-get update
          sudo apt-get install -y musl-tools
        fi

    - name: Determine build tool
      id: build-tool
      shell: bash
      run: |
        # Determine if we should use cargo (native) or cross (Docker)
        # Use cargo for: darwin, native aarch64, Windows GNU
        # Use cross for: everything else (cross-compilation)
        if [[ "${{ inputs.os-name }}" == *"darwin"* ]] || \
           [[ "${{ inputs.target }}" == *"aarch64"* && "$(uname -m)" == "aarch64" ]] || \
           [[ "${{ inputs.target }}" == *"windows-gnu"* ]]; then
          echo "BUILD_TOOL=cargo" >> $GITHUB_ENV
        else
          echo "BUILD_TOOL=cross" >> $GITHUB_ENV
          cargo install cross --version 0.2.5 --force
        fi

    - name: Update Bundle CLI version
      uses: ./.github/actions/update_version
      if: inputs.release_tag != ''
      with:
        version: ${{ inputs.release_tag }}
        file: ./bundle/Cargo.toml

    - name: Update XCResult CLI version
      uses: ./.github/actions/update_version
      if: inputs.release_tag != ''
      with:
        version: ${{ inputs.release_tag }}
        file: ./xcresult/Cargo.toml

    - name: Update Codeowners CLI version
      uses: ./.github/actions/update_version
      if: inputs.release_tag != ''
      with:
        version: ${{ inputs.release_tag }}
        file: ./codeowners/Cargo.toml

    - name: Build Bundle CLI
      shell: bash
      run: |
        ${{ env.BUILD_TOOL }} build -p bundle --profile=release-with-debug --target=${{ inputs.target }} --features build-binary

    - name: Build XCResult CLI
      shell: bash
      run: |
        ${{ env.BUILD_TOOL }} build -p xcresult --profile=release-with-debug --target=${{ inputs.target }}

    - name: Build Codeowners CLI
      shell: bash
      run: |
        ${{ env.BUILD_TOOL }} build -p codeowners --profile=release-with-debug --target=${{ inputs.target }}
