name: Setup Proto
description: Setup Proto

runs:
  using: composite
  steps:
    - name: Install cmake
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install cmake -y
      shell: bash
