name: Test Ruby Gem Release
description: Run stable tests for a Ruby gem release
author: trunk.io

inputs:
  ruby-version:
    description: Ruby versions to test
    required: true
  artifact-pattern:
    default: cross-gem-*
    description: Artifact pattern to download
    required: false
  trunk-token:
    description: Trunk API token
    required: true
  trunk-public-api-address:
    description: Trunk public API address
    required: false
    default: https://api.trunk-staging.io
  trunk-org-slug:
    description: The organization to upload the tests for
    required: false
    default: trunk-staging-org
  platform:
    description: The platform that the gem was built for
    required: true
  knapsack-pro-test-suite-token-rspec:
    description: Optional Knapsack Pro test suite token for RSpec
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ github.action_path }}

    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact-pattern }}
        path: ${{ github.action_path }}
        merge-multiple: true

    - name: Setup gem
      id: setup-gem
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        gem install rspec
        GEM_FILE=$(ls rspec_trunk_flaky_tests-*.gem | head -n 1)
        echo "Using gem file: ${GEM_FILE}"

        # Extract version from gem filename (e.g., rspec_trunk_flaky_tests-0.0.0-b75353b-x86_64-linux.gem)
        PLATFORM="${{ inputs.platform }}"
        GEM_VERSION=$(echo "${GEM_FILE}" | sed -n "s/rspec_trunk_flaky_tests-\(.*\)-${PLATFORM}\.gem/\1/p")
        echo "Extracted version: ${GEM_VERSION}"

        gem install "${GEM_FILE}" --local
        # Unpack the specific gem file directly, not from installed gems
        mkdir -p rspec_trunk_flaky_tests
        gem unpack "${GEM_FILE}" --spec --target=rspec_trunk_flaky_tests
        gem unpack "${GEM_FILE}" --target=rspec_trunk_flaky_tests
        mv rspec_trunk_flaky_tests/rspec_trunk_flaky_tests*/lib rspec_trunk_flaky_tests/lib
        bundle install
        sed -i "s|gem 'rspec_trunk_flaky_tests'.*|gem 'rspec_trunk_flaky_tests', '${GEM_VERSION}', :path => './rspec_trunk_flaky_tests'|" Gemfile
        bundle lock --remove-platform ruby || true
        bundle install --gemfile Gemfile --local

    # - name: Run regular tests
    #   id: run-regular-tests
    #   shell: bash
    #   working-directory: ${{ github.action_path }}
    #   run: |
    #     bundle exec rspec spec/test_spec.rb --format documentation
    #   env:
    #     TRUNK_PUBLIC_API_ADDRESS: ${{ inputs.trunk-public-api-address }}
    #     TRUNK_ORG_URL_SLUG: ${{ inputs.trunk-org-slug }}
    #     TRUNK_API_TOKEN: ${{ inputs.trunk-token }}

    # - name: Run variant quarantine test without variant (should fail - not quarantined)
    #   id: run-variant-test-no-variant
    #   shell: bash
    #   working-directory: ${{ github.action_path }}
    #   run: |
    #     set +e
    #     bundle exec rspec spec/variant_quarantine_spec.rb --format documentation
    #     EXIT_CODE=$?
    #     if [ $EXIT_CODE -eq 0 ]; then
    #       echo "ERROR: Variant quarantine test without variant should have failed (test should not be quarantined)"
    #       exit 1
    #     else
    #       echo "SUCCESS: Variant quarantine test without variant failed as expected (test is not quarantined)"
    #     fi
    #   env:
    #     TRUNK_PUBLIC_API_ADDRESS: ${{ inputs.trunk-public-api-address }}
    #     TRUNK_ORG_URL_SLUG: ${{ inputs.trunk-org-slug }}
    #     TRUNK_API_TOKEN: ${{ inputs.trunk-token }}
    #     TRUNK_VARIANT: ""

    # - name: Run variant quarantine test with variant (should pass - quarantined)
    #   id: run-variant-test-with-variant
    #   shell: bash
    #   working-directory: ${{ github.action_path }}
    #   run: |
    #     bundle exec rspec spec/variant_quarantine_spec.rb --format documentation
    #     EXIT_CODE=$?
    #     if [ $EXIT_CODE -ne 0 ]; then
    #       echo "ERROR: Variant quarantine test with variant should have passed (test should be quarantined)"
    #       echo "Note: The variant_quarantine_test must be quarantined with variant 'smoke-test-variant' in the system"
    #       exit 1
    #     else
    #       echo "SUCCESS: Variant quarantine test with variant passed (test was quarantined)"
    #     fi
    #   env:
    #     TRUNK_PUBLIC_API_ADDRESS: ${{ inputs.trunk-public-api-address }}
    #     TRUNK_ORG_URL_SLUG: ${{ inputs.trunk-org-slug }}
    #     TRUNK_API_TOKEN: ${{ inputs.trunk-token }}
    #     TRUNK_VARIANT: smoke-test-variant

    - name: Run knapsack_pro queue and verify a single local bundle
      shell: bash
      if: inputs.knapsack-pro-test-suite-token-rspec != ''
      working-directory: ${{ github.action_path }}
      env:
        KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ inputs.knapsack-pro-test-suite-token-rspec }}
        KNAPSACK_PRO_CI_NODE_TOTAL: 3
        KNAPSACK_PRO_CI_NODE_INDEX: 1
        # https://docs.knapsackpro.com/ruby/queue-mode/#dynamic-split-vs-fixed-split
        KNAPSACK_PRO_FIXED_QUEUE_SPLIT: false
        TRUNK_API_TOKEN: ${{ inputs.trunk-token }}
        TRUNK_ORG_URL_SLUG: ${{ inputs.trunk-org-slug }}
        TRUNK_PUBLIC_API_ADDRESS: ${{ inputs.trunk-public-api-address }}
        TRUNK_LOCAL_UPLOAD_DIR: bundles
      run: |
        set -euo pipefail
        rm -rf "${TRUNK_LOCAL_UPLOAD_DIR}"
        mkdir -p "${TRUNK_LOCAL_UPLOAD_DIR}"
        set +e
        # Initialize is not required, but some custom setups will use it
        bundle exec rake "knapsack_pro:queue:rspec:initialize"

        if [ -d "${TRUNK_LOCAL_UPLOAD_DIR}" ]; then
          echo "knapsack_pro manual queue initialization should not trigger an upload"
          ls -la "${TRUNK_LOCAL_UPLOAD_DIR}"
          exit 1
        fi

        OUTPUT_FILE=$(mktemp)
        bundle exec rake "knapsack_pro:queue:rspec" 2>&1 | tee "${OUTPUT_FILE}"
        set -e
        OUTPUT=$(cat "${OUTPUT_FILE}")
        rm -f "${OUTPUT_FILE}"

        if [ ! -d "${TRUNK_LOCAL_UPLOAD_DIR}" ]; then
          echo "Expected ${TRUNK_LOCAL_UPLOAD_DIR} directory to be created"
          exit 1
        fi

        REPORT_COUNT=$(echo "${OUTPUT}" | grep -c "Local Flaky tests report generated" || echo "0")
        if [ "${REPORT_COUNT}" -ne 1 ]; then
          echo "Expected 'Local Flaky tests report generated' to appear exactly once, found ${REPORT_COUNT} times"
          exit 1
        fi

        echo "Knapsack run correctly generated exactly one bundle at ${bundle_files[0]}"
