# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rspec'
gem 'knapsack_pro'
gem 'rake'
gem 'rake-compiler'
gem 'logger'
gem 'rspec_trunk_flaky_tests', :path => '../../../rspec-trunk-flaky-tests'
