[package]
name = "display"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.44"
# TODO: Switch to superconsole 0.3.0 once it's released: https://github.com/facebookincubator/superconsole/issues/13
superconsole = { git = "https://github.com/facebookincubator/superconsole.git", rev = "31719d7b7357fc6a22ec0cb52bfeaac5add8152e" }
tracing = "0.1.41"
terminal_size = "0.4.2"
