[package]
name = "context-ruby"
version = "0.1.0"
edition = "2021"

[lib]
name = "context_ruby"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.93"
context = { path = "../context", features = ["git-access", "ruby"] }
magnus = { version = "0.7", features = ["embed"] }
