# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rake'
gem 'rake-compiler', '1.2.0'
gem 'rspec'
gem 'rspec-core'
gem 'test-unit'

# gem 'rake-release'
gem 'rb_sys', '=0.9.98'

# gem "rake-compiler-dock", "~> 1.8"
# gem "libclang", "~> 14.0.6"
