# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake'
gem 'rake-compiler', '1.2.0'
gem 'rspec'
gem 'rspec-core'
gem 'test-unit'
gem 'rspec_junit_formatter'

gem 'rb_sys', '~> 0.9.103'
