name: Setup Rust & Cargo
description: Setup Rust & Cargo

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-unknown-unknown

    - name: Install protoc
      shell: bash
      run: |
        if [ -f /opt/homebrew/bin/brew ]; then
          /opt/homebrew/bin/brew install protobuf
        elif [ -f /usr/bin/apt ]; then
          sudo /usr/bin/apt update
          sudo /usr/bin/apt install -y protobuf-compiler
        fi

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.arch }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
