name: Perform Smoke Test
description: Runs the actual smoke tests

inputs:
  cli-binary-location:
    description: Location for the cli binary, relative to current directory. Supports both Unix and Windows binaries.
    required: true
  staging-api-token:
    description: Api token for the trunk-staging-org org on trunk-staging (should be available in secrets)
    required: true
  production-api-token:
    description: Api token for the trunk org on trunk (should be available in secrets)
    required: true
  environment-type:
    description: staging if you only want to run for staging, production if you only want production, both for both
    default: both
  test-variants:
    description: Whether to test variant quarantining (only supported in main branch builds)
    default: "false"

outputs:
  production-success:
    description: True if we ran and uploaded to production
    value: ${{ steps.production-result.outputs.production-success }}
  staging-success:
    description: True if we ran and uploaded to staging
    value: ${{ steps.staging-result.outputs.staging-success }}

runs:
  using: composite
  steps:
    - name: Verify binary exists
      id: verify-binary
      shell: bash
      run: |
        if [ ! -f "${{ inputs.cli-binary-location }}" ]; then
          echo "Binary not found at: ${{ inputs.cli-binary-location }}"
          exit 1
        fi
        chmod +x ${{ inputs.cli-binary-location }} || true
        openssl dgst -sha256 "${{ inputs.cli-binary-location }}" | awk '{print $NF}'
        ls -l "${{ inputs.cli-binary-location }}"

    - name: Setup Swift
      if: runner.os == 'macOS'
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Run tests on staging
      id: staging-test-run
      if: always() && steps.verify-binary.outcome == 'success' && (inputs.environment-type == 'staging' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk-staging-org \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.staging-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Run Swift tests
      id: xcresult-swift-test-run
      continue-on-error: true
      if: runner.os == 'macos'
      working-directory: smoke-test/swift
      shell: bash
      run: |
        xcodebuild test -workspace smoke-test.xcworkspace -scheme SmokeTestTests -destination 'platform=macOS' -resultBundlePath TestResults.xcresult -enableCodeCoverage YES

    - name: Upload Swift tests on staging
      id: xcresult-staging-upload
      if: always() && runner.os == 'macos'
      shell: bash
      run: |
        # Map GitHub Actions step outcome to exit code
        # outcome can be: success, failure, cancelled, skipped
        # success -> 0, failure/cancelled -> 1, skipped -> 0
        if [ "${{ steps.xcresult-swift-test-run.outcome }}" == "success" ]; then
          EXIT_CODE=0
        elif [ "${{ steps.xcresult-swift-test-run.outcome }}" == "failure" ] || [ "${{ steps.xcresult-swift-test-run.outcome }}" == "cancelled" ]; then
          EXIT_CODE=1
        else
          # skipped or unknown
          EXIT_CODE=0
        fi
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk-staging-org \
        --xcresult-path smoke-test/swift/TestResults.xcresult \
        --token ${{ inputs.staging-api-token }} \
        --test-process-exit-code $EXIT_CODE
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io

    - name: Upload to staging
      id: staging-upload
      if: always() && steps.staging-test-run.outcome == 'success' && (inputs.environment-type == 'staging' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk-staging-org \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.staging-api-token }}

    # upload with variant should fail because we treat variant as a separate test
    - name: Upload to staging with variant
      id: staging-upload-with-variant
      if: always() && inputs.test-variants == 'true' && steps.staging-test-run.outcome == 'success' && (inputs.environment-type == 'staging' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
      shell: bash
      run: |
        set +e
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk-staging-org \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.staging-api-token }} \
        --variant smoke-test-variant
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 0 ]; then
          echo "ERROR: Expected upload with variant to fail, but it succeeded"
          exit 1
        else
          echo "SUCCESS: Upload with variant failed as expected (exit code: $EXIT_CODE)"
          exit 0
        fi

    - name: Staging result
      id: staging-result
      if: always()
      shell: bash
      run: |
        if [ "${{ inputs.test-variants }}" == "true" ]; then
          echo "staging-success=${{ (steps.staging-upload.outcome == 'success' && steps.staging-upload-with-variant.outcome == 'success' && (inputs.environment-type == 'staging' || inputs.environment-type == 'both')) || inputs.environment-type == 'production' }}" >> $GITHUB_OUTPUT
        else
          echo "staging-success=${{ (steps.staging-upload.outcome == 'success' && (inputs.environment-type == 'staging' || inputs.environment-type == 'both')) || inputs.environment-type == 'production' }}" >> $GITHUB_OUTPUT
        fi

    - name: Run tests on production
      id: production-test-run
      if: always() && steps.verify-binary.outcome == 'success' && (inputs.environment-type == 'production' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.production-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Upload Swift tests on production
      id: xcresult-production-upload
      if: always() && runner.os == 'macos'
      shell: bash
      run: |
        # Map GitHub Actions step outcome to exit code
        # outcome can be: success, failure, cancelled, skipped
        # success -> 0, failure/cancelled -> 1, skipped -> 0
        if [ "${{ steps.xcresult-swift-test-run.outcome }}" == "success" ]; then
          EXIT_CODE=0
        elif [ "${{ steps.xcresult-swift-test-run.outcome }}" == "failure" ] || [ "${{ steps.xcresult-swift-test-run.outcome }}" == "cancelled" ]; then
          EXIT_CODE=1
        else
          # skipped or unknown
          EXIT_CODE=0
        fi
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk \
        --xcresult-path smoke-test/swift/TestResults.xcresult \
        --token ${{ inputs.production-api-token }} \
        --test-process-exit-code $EXIT_CODE
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io

    - name: Upload to production
      id: production-upload
      if: always() && steps.production-test-run.outcome == 'success' && (inputs.environment-type == 'production' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.production-api-token }}

    # upload with variant should fail because we treat variant as a separate test
    - name: Upload to production with variant
      id: production-upload-with-variant
      if: always() && inputs.test-variants == 'true' && steps.production-test-run.outcome == 'success' && (inputs.environment-type == 'production' || inputs.environment-type == 'both')
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
      shell: bash
      run: |
        set +e
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk \
        --junit-paths "${{ github.workspace }}/target/**/*junit.xml" \
        --token ${{ inputs.production-api-token }} \
        --variant smoke-test-variant
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 0 ]; then
          echo "ERROR: Expected upload with variant to fail, but it succeeded"
          exit 1
        else
          echo "SUCCESS: Upload with variant failed as expected (exit code: $EXIT_CODE)"
          exit 0
        fi

    - name: Production result
      id: production-result
      if: always()
      shell: bash
      run: |
        if [ "${{ inputs.test-variants }}" == "true" ]; then
          echo "production-success=${{ (steps.production-upload.outcome == 'success' && steps.production-upload-with-variant.outcome == 'success' && (inputs.environment-type == 'production' || inputs.environment-type == 'both')) || inputs.environment-type == 'staging' }}" >> $GITHUB_OUTPUT
        else
          echo "production-success=${{ (steps.production-upload.outcome == 'success' && (inputs.environment-type == 'production' || inputs.environment-type == 'both')) || inputs.environment-type == 'staging' }}" >> $GITHUB_OUTPUT
        fi
