name: Perform Smoke Test
description: Runs the actual smoke tests

inputs:
  cli-binary-location:
    description: Location for the cli binary, relative to current directory. Uses x86_64-unknown-linux binaries.
  staging-api-token:
    description: Api token for the trunk-staging-org org on trunk-staging (should be available in secrets)
  production-api-token:
    description: Api token for the trunk org on trunk (should be available in secrets)
  environment-type:
    description: staging if you only want to run for staging, production if you only want production, both for both
  platform-name:
    description: Name of the platform being used, eg 'x86_64-linux', 'x86_64-darwin', 'arm64-darwin'
  use-local-rspec:
    description: True if we should use a locally built rspec, false if we should use the rubygems version
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Make executable
      shell: bash
      run: |
        chmod +x ${{ inputs.cli-binary-location }}
        openssl dgst -sha256 ${{ inputs.cli-binary-location }} | awk '{print $NF}'
        ls -l ${{ inputs.cli-binary-location }}

    - name: Run tests on staging
      if: inputs.environment-type == 'staging' || inputs.environment-type == 'both'
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk-staging-org \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.staging-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Run tests on production
      if: inputs.environment-type == 'production' || inputs.environment-type == 'both'
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.production-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Upload to staging
      if: inputs.environment-type == 'staging' || inputs.environment-type == 'both'
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk-staging-org \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.staging-api-token }}

    - name: Upload to production
      if: inputs.environment-type == 'production' || inputs.environment-type == 'both'
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.production-api-token }}

    - name: Install ruby helper
      if: inputs.use-local-rspec
      shell: bash
      working-directory: context-ruby
      run: |
        gem install rspec_trunk_flaky_tests-*.gem --local
        gem unpack rspec_trunk_flaky_tests* --spec --target=rspec_trunk_flaky_tests
        gem unpack rspec_trunk_flaky_tests* --target=rspec_trunk_flaky_tests
        mv rspec_trunk_flaky_tests/rspec_trunk_flaky_tests*/lib ../smoke-test/rspec_trunk_flaky_tests/lib

    - name: Add ruby helper to gemfile when built
      if: inputs.use-local-rspec
      shell: bash
      working-directory: smoke-test
      run: |
        echo "gem 'rspec_trunk_flaky_tests', :path => './rspec_trunk_flaky_tests'" >> Gemfile

    - name: Add ruby helper to gemfile when built
      if: not inputs.use-local-rspec
      shell: bash
      working-directory: smoke-test
      run: |
        echo "gem 'rspec_trunk_flaky_tests'" >> Gemfile

    - name: Test rspec on staging
      if: inputs.environment-type == 'staging' || inputs.environment-type == 'both'
      shell: bash
      working-directory: smoke-test
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
        TRUNK_ORG_URL_SLUG: trunk-staging-org
        TRUNK_API_TOKEN: ${{ inputs.staging-api-token }}
      run: |
        gem install rspec
        bundle install
        bundle lock --remove-platform ruby || true
        bundle install --gemfile Gemfile --local
        bundle exec rspec spec/test_spec.rb

    - name: Test rspec on production
      if: inputs.environment-type == 'production' || inputs.environment-type == 'both'
      uses: ./.github/actions/test_ruby_gem_uploads
      with:
        ruby-version: "3.4"
        trunk-token: ${{ inputs.production-api-token }}
        platform: ${{ inputs.platform-name }}
        artifact-pattern: ${{ inputs.rspec-helper-location }}
