name: Perform Smoke Test
description: Runs the actual smoke tests
#TODO secrets.TRUNK_ORG_API_TOKEN is not a real secret yet, gotta get an admin to add it to github

inputs:
  cli-binary-location:
    description: Location for the cli binary, relative to current directory. Uses x86_64-unknown-linux binaries.
  staging-api-token:
    description: Api token for the trunk-staging-org org on trunk-staging (should be available in secrets)
  production-api-token:
    description: Api token for the trunk org on trunk (should be available in secrets)

runs:
  using: composite
  steps:
    - name: Make executable
      shell: bash
      run: |
        chmod +x ${{ inputs.cli-binary-location }}

    - name: Run tests on staging
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk-staging-org \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.staging-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Run tests on production
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
        FAIL_TEST: true
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} test \
        --org-url-slug trunk \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.production-api-token }} \
        cargo nextest run -p smoke-test --profile ci

    - name: Upload to staging
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk-staging-org \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.staging-api-token }}

    - name: Upload to production
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
      shell: bash
      run: |
        ./${{ inputs.cli-binary-location }} upload \
        --org-url-slug trunk \
        --junit-paths ${{ github.workspace }}/target/**/*junit.xml \
        --token ${{ inputs.production-api-token }}
