name: Setup Ruby
description: Setup Ruby

runs:
  using: composite
  steps:
    - name: Update and install libclang-dev
      run: |
        sudo apt update
        sudo apt-get install libclang-dev -y
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        working-directory: context-ruby

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        working-directory: smoke-test
