name: Setup and build pyo3
description: Setup and build pyo3

runs:
  using: composite
  steps:
    - name: Setup Rust & Cargo
      uses: ./.github/actions/setup_rust_cargo

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip

    - name: Install dependencies
      shell: bash
      run: |
        pip install uv
        uv venv --system ./context-py/.venv
        source ./context-py/.venv/bin/activate
        uv pip install -r ./context-py/requirements-dev.txt
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
        echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH

    - name: Generate Python stubs
      shell: bash
      run: ${TRUNK_PATH} run generate-pyi

    - name: Build pyo3 package
      shell: bash
      run: |
        maturin dev --manifest-path ./context-py/Cargo.toml
