name: Build and test context-ruby

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust & Cargo
        uses: ./.github/actions/setup_rust_cargo

      - name: Setup Ruby
        uses: ./.github/actions/setup_ruby

      - name: Test ruby package
        if: "!cancelled()"
        run: |
          bundle install
          bundle exec rake test
        working-directory: context-ruby
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
          TRUNK_ORG_URL_SLUG: trunk-staging-org
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
