name: Build and test context-ruby

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: public-amd64-2xlarge
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust & Cargo
        uses: ./.github/actions/setup_rust_cargo

      # TODO - migrate away from ubuntu-latest and put this in setup_rust_cargo
      - name: Update and install libclang-dev
        run: |
          sudo apt update
          sudo apt-get install libclang-dev -y

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          working-directory: context-ruby

      - name: Test ruby package
        if: "!cancelled()"
        run: |
          bundle install
          bundle exec rake test
        working-directory: context-ruby
