name: Build and test context-ruby

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
        working-directory: context-ruby

      - name: Test ruby package
        if: "!cancelled()"
        run: bundle exec rake test
        working-directory: context-ruby
