name: Setup Run Smoke Tests
description: Perform setup needed to run smoke tests

runs:
  using: composite
  steps:
    - name: Setup Rust & Cargo
      uses: ./.github/actions/setup_rust_cargo

    - name: Install nextest (darwin)
      if: runner.os == 'macOS'
      uses: taiki-e/install-action@nextest

    - name: Install nextest (linux x86)
      if: runner.os == 'Linux'
      shell: bash
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      
    - name: Install nextest (windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $tempDir = New-Item -ItemType Directory -Path (Join-Path $env:TEMP ([System.Guid]::NewGuid().ToString())) -Force
        Invoke-WebRequest -Uri "https://get.nexte.st/latest/windows" -OutFile "$tempDir\nextest.zip"
        Expand-Archive -Path "$tempDir\nextest.zip" -DestinationPath "$env:USERPROFILE\.cargo\bin" -Force
        Remove-Item -Path $tempDir -Recurse -Force
