name: Setup Run Smoke Tests
description: Perform setup needed to run smoke tests

runs:
  using: composite
  steps:
    - name: Setup Rust & Cargo
      uses: ./.github/actions/setup_rust_cargo

    - name: Install Nextest
      shell: bash
      run: |
        cargo install --version 0.9.85 cargo-nextest --locked

    - name: Install cmake
      shell: bash
      run: |
        sudo apt-get install cmake -y
