name: Setup Run Smoke Tests
description: Perform setup needed to run smoke tests

runs:
  using: composite
  steps:
    - name: Setup Rust & Cargo
      uses: ./.github/actions/setup_rust_cargo

    - name: Install nextest (darwin)
      if: runner.os == 'macOS'
      uses: taiki-e/install-action@nextest

    - name: Cache nextest binary (Linux)
      uses: actions/cache@v4
      id: cache-nextest-linux
      if: runner.os == 'Linux'
      with:
        path: ~/.cargo/bin/cargo-nextest
        key: nextest-linux-latest

    - name: Cache nextest binary (Windows)
      uses: actions/cache@v4
      id: cache-nextest-windows
      if: runner.os == 'Windows'
      with:
        path: ~/.cargo/bin/cargo-nextest
        key: nextest-windows-latest

    - name: Install nextest (linux x86)
      if: runner.os == 'Linux' && steps.cache-nextest-linux.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${CARGO_HOME:-~/.cargo}/bin
        curl -LsSf --retry 5 --retry-all-errors --retry-delay 2 https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Install nextest (windows)
      if: runner.os == 'Windows' && steps.cache-nextest-windows.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        $cargoBin = if ($env:CARGO_HOME) { "$env:CARGO_HOME\bin" } else { "$env:USERPROFILE\.cargo\bin" }
        Invoke-WebRequest -Uri "https://get.nexte.st/latest/windows" -OutFile "$env:TEMP\nextest.zip"
        Expand-Archive -Path "$env:TEMP\nextest.zip" -DestinationPath $cargoBin -Force
