name: Setup Run Smoke Tests
description: Perform setup needed to run smoke tests

runs:
  using: composite
  steps:
    - name: Setup Rust & Cargo
      uses: ./.github/actions/setup_rust_cargo

    - name: Install nextest (darwin)
      if: runner.os == 'macOS'
      uses: taiki-e/install-action@nextest

    - name: Install nextest (linux x86)
      if: runner.os == 'Linux'
      shell: bash
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Install nextest (windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $cargoBin = if ($env:CARGO_HOME) { "$env:CARGO_HOME\bin" } else { "$env:USERPROFILE\.cargo\bin" }
        Invoke-WebRequest -Uri "https://get.nexte.st/latest/windows" -OutFile "$env:TEMP\nextest.zip"
        Expand-Archive -Path "$env:TEMP\nextest.zip" -DestinationPath $cargoBin -Force
